// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlqbqfptjezsbljhaffa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscWJxZnB0amV6c2JsamhhZmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjcyMjcsImV4cCI6MjA2MDIwMzIyN30.ioJ0tcbZD8s3Z2_2Ls6N8VB8V3V1YQJ_vfVOkd3Dnhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);